// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe4VgOYaoI7RXBng8SsRtpS4z-ImrIajo',
    appId: '1:316116460437:android:e3d45da8c9add841660c9c',
    messagingSenderId: '316116460437',
    projectId: 'trimbo-66bf9',
    authDomain: 'trimbo-66bf9.firebaseapp.com',
    storageBucket: 'trimbo-66bf9.firebasestorage.app',
    measurementId: 'G-HNDRYT4K3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe4VgOYaoI7RXBng8SsRtpS4z-ImrIajo',
    appId: '1:316116460437:android:e3d45da8c9add841660c9c',
    messagingSenderId: '316116460437',
    projectId: 'trimbo-66bf9',
    storageBucket: 'trimbo-66bf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe4VgOYaoI7RXBng8SsRtpS4z-ImrIajo',
    appId: '1:316116460437:android:e3d45da8c9add841660c9c',
    messagingSenderId: '316116460437',
    projectId: 'trimbo-66bf9',
    storageBucket: 'trimbo-66bf9.firebasestorage.app',
    iosBundleId: 'com.trimbo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe4VgOYaoI7RXBng8SsRtpS4z-ImrIajo',
    appId: '1:316116460437:android:e3d45da8c9add841660c9c',
    messagingSenderId: '316116460437',
    projectId: 'trimbo-66bf9',
    storageBucket: 'trimbo-66bf9.firebasestorage.app',
    iosBundleId: 'com.trimbo.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe4VgOYaoI7RXBng8SsRtpS4z-ImrIajo',
    appId: '1:316116460437:android:e3d45da8c9add841660c9c',
    messagingSenderId: '316116460437',
    projectId: 'trimbo-66bf9',
    authDomain: 'trimbo-66bf9.firebaseapp.com',
    storageBucket: 'trimbo-66bf9.firebasestorage.app',
    measurementId: 'G-HNDRYT4K3L',
  );
}